<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="ViewModels\" />
		<Folder Include="Views\Account\" />
		<Folder Include="Views\Area\" />
		<Folder Include="Views\Client\" />
		<Folder Include="Views\Home\" />
		<Folder Include="Views\Inventory\" />
		<Folder Include="Views\Manager\" />
		<Folder Include="Views\NewFolder\" />
		<Folder Include="Views\Product\" />
		<Folder Include="Views\Shared\" />
		<Folder Include="Views\User\" />
		<Folder Include="Views\Visit\" />
	</ItemGroup>

</Project>
